server: 
  profiles: 
  active: 
  - dev
---
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-dzl-dev
---  
spring: 
  profiles: test
  application:
    name: microservicecloud-config-dzl-test